### ISSUE TITLE
Suggest to update to handle breaking changes in Home Assistant 2021.9

### ISSUE THREAD

**Issue by emontnemery** [And3rsL/Deebot-for-Home-Assistant#181]
### Suggested change

The `SensorEntity` base component will change in HomeAssistant core 2021.9 such that classes extending it should no longer directly set the `state` or `unit_of_measurement`, background in https://github.com/home-assistant/core/pull/48261.

Classes extending `SensorEntity` should now instead set `_attr_native_value` or override the `native_value` method, as well as set the `_attr_native_unit_of_measurement` or override the `unit_of_measurement` method.

As part of those changes, the `_attr_state` shorthand is planned to be removed from `SensorEntity`, but it will still work to override the `state` method (although not recommended), see https://github.com/home-assistant/core/pull/54624.

The changes in https://github.com/home-assistant/core/pull/54624 will most likely land in HomeAssistant Core 2021.9.

Note: These changes won't break `Deebot-for-Home-Assistant` as the sensors don't inherit `SensorEntity` but instead inherit `Entity`

**Comment by edenhaus** [comment]
Thanks fir the hint :) I will give it at look, when the `rc` is out.

As you are involved in the HA development, I have a question regarding this change. Is there a way for a custom_integration to specify, which version is compatible with which HA version?
I remember me, that there was a key in the `manifest`, but it was removed. The point is, that with version 3+ I'm using `_attr_name`, which as introduced in `2021.6` and in august someone reported an issue, that their name was not set correctly (#161). At the end the problem was that they didn't update HA that often and stayed on `2021.5`
So when I implement your suggestion, it will break the component for all HA version below `2021.9`
